"""Initial migration

Revision ID: 9334f60df61c
Revises: 001
Create Date: 2025-05-03 15:06:53.137807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9334f60df61c'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_history_image_id', table_name='analysis_history')
    op.drop_index('ix_analysis_history_prediction_id', table_name='analysis_history')
    op.drop_index('ix_analysis_history_user_id', table_name='analysis_history')
    op.add_column('images', sa.Column('image_metadata', sa.JSON(), nullable=True))
    op.drop_index('ix_images_user_id', table_name='images')
    op.drop_column('images', 'metadata')
    op.drop_index('ix_predictions_image_id', table_name='predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_predictions_image_id', 'predictions', ['image_id'], unique=False)
    op.add_column('images', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_images_user_id', 'images', ['user_id'], unique=False)
    op.drop_column('images', 'image_metadata')
    op.create_index('ix_analysis_history_user_id', 'analysis_history', ['user_id'], unique=False)
    op.create_index('ix_analysis_history_prediction_id', 'analysis_history', ['prediction_id'], unique=False)
    op.create_index('ix_analysis_history_image_id', 'analysis_history', ['image_id'], unique=False)
    # ### end Alembic commands ### 